name: Auto Deploy on Commit

on:
  push:
    branches:
      - master

jobs:
  publish-docker-hub:
    name: build and publish image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Dockerhu
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mayhem49/docker-ci-cd:latest

